### PR TITLE
Add some basic trig functions

### PR DESCRIPTION
**Pull request by hovind**
Just lazily adding some trig functions I needed, more might come later.

### CODE REVIEW

**Comment by maplant** [comment]
Would you mind holding off on this until you have a concrete use case for it? I think it technically counts as a breaking change, in which case I think it should be merged with a change in version number, something I might do if it's decided to rename the library to al-jabr

However, if you need it for something that you can't push yet I'm happy to merge it anyway

**Comment by hovind** [comment]
> Would you mind holding off on this until you have a concrete use case for it? I think it technically counts as a breaking change, in which case I think it should be merged with a change in version number, something I might do if it's decided to rename the library to al-jabr
> 
> However, if you need it for something that you can't push yet I'm happy to merge it anyway

Just using it for some experiments, which are blocked by https://github.com/rust-lang/rust/issues/60551 regardless, so no rush at all. :)

**Comment by maplant** [comment]
If you have any use cases for this I would be happy to merge this (and the use cases) now. I'm planning on re-releasing aljabar under the more correct name al-jabr, and reset the version. Thus no worries on breaking changes.

**Comment by hovind** [comment]
> If you have any use cases for this I would be happy to merge this (and the use cases) now. I'm planning on re-releasing aljabar under the more correct name al-jabr, and reset the version. Thus no worries on breaking changes.

Sorry for the late response, @maplant, I've been away for a short while. I can add the full set of trig functions and inverses later today, do you want the hyperbolic versions included? Have you given any thought to what trait they belong under? They seem perfect where they are, the only wart I can see is `impl<T> Real for Complex<T>`, but I guess that's non-issue. Should the `Real`-trait implement the common https://doc.rust-lang.org/std/primitive.f64.html#methods and https://doc.rust-lang.org/std/primitive.f32.html#methods interface?

**Review by maplant — APPROVED** [review]
I don't really have any reason to not add these if they make generic code easier to write

**Pull request merged**
